service: favorites
frameworkVersion: '3.25.1'
plugins:
  - serverless-python-requirements
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  runtime: python3.8
  lambdaHashingVersion: 20201221                 
  httpApi:
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: ${param:users_authorizer_issuer_url}
        audience: ${param:user_pool_client_arn}
  environment:
    FAVORITES_TABLE_NAME: ${self:custom.FAVORITES_TABLE_NAME}
    USERS_HTTP_API_URL: ${cf:users-dev.HttpApiUrl}
    MAX_LIST_SIZE: 20
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - 'dynamodb:PutItem'
        - 'dynamodb:Query'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource:
        Fn::GetAtt: [FavoritesDynamoDBTable, Arn]
custom:
  FAVORITES_TABLE_NAME: ${self:provider.stage}-${self:service}-favorites-table
functions:
  sign_up:
    handler: src/functions/sign_up/handler.handler
    events:
      - httpApi:
          path: /users
          method: POST
  create_list:
    handler: src/functions/create_list/handler.handler
    events:
      - httpApi:
          path: /lists
          method: POST
          authorizer: serviceAuthorizer
  list_all_lists_per_user:
    handler: src/functions/get_user_lists/handler.handler
    events:
      - httpApi:
          path: /lists
          method: GET  
          authorizer: serviceAuthorizer          
  update_list_metadata:
    handler: src/functions/update_list_metadata/handler.handler
    events:
      - httpApi:
          path: /lists/{list_id}
          method: PATCH
          authorizer: serviceAuthorizer
  update_list_contents:
    handler: src/functions/update_list_contents/handler.handler
    events:
      - httpApi:
          path: /lists/{list_id}
          method: PUT
          authorizer: serviceAuthorizer
  get_list_by_list_id:
    handler: src/functions/get_list/handler.handler
    private: true
    events:
      - httpApi:
          path: /lists/{list_id}
          method: GET
          authorizer: serviceAuthorizer
  delete_list:
    handler: src/functions/delete_list/handler.handler
    private: true
    events:
      - httpApi:
          path: /lists/{list_id}
          method: DELETE
          authorizer: serviceAuthorizer                  
resources:
  Resources:
    FavoritesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.FAVORITES_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE               
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1               

  Outputs:
    tableName:
      Value: ${self:custom.FAVORITES_TABLE_NAME}
    tableArn:
      Value:
        Fn::GetAtt: [FavoritesDynamoDBTable, Arn]
    usersHttpApiUrl:
      Value: ${cf:users-dev.HttpApiUrl}